name: ez_listenable_angular
description: A library that connects EzListenable classes to AngularDart components
version: 0.1.0
homepage: https://github.com/brianegan/ez_listenable
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  ez_listenable:
    path: ../ez_listenable

dev_dependencies:
  angular_test: ^2.0.0
  test: ^1.0.0
  mockito: ^4.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.2+2


