name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: phillywiggins <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: ^2.0.8
  http: ^0.12.0
  ez_listenable:
    path: ../../ez_listenable

dev_dependencies:
  test: ^1.5.0
  mockito: ^4.0.0
  ez_listenable_test:
    path: ../../ez_listenable_test
